### ISSUE TITLE
Error compiling Cython file: adversarial/lib/transformations/tv_bregman.pyx:10:0: relative cimport beyond main package is not allowed

### ISSUE THREAD

**Issue by nishamuktewar** [facebookresearch/adversarial_image_defenses#8]
Hi,

Any insights that you can share on this error? Attaching the complete output when I do "pip install .".

My current environment:
Python: 2.7

(FB_env) nisha@xxx:/adversarial_image_defenses$ python -c "import faiss"
(FB_env) nisha@xxx:/adversarial_image_defenses$ python -c "import torch; print(torch.__version__)"
0.4.0
(FB_env) nisha@xxx:/adversarial_image_defenses$ python -c "import torchvision; print(torchvision.__version__)"
0.2.1
(FB_env) nisha@xxx:/adversarial_image_defenses$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
(FB_env) nisha@toymaker:/adversarial_image_defenses$ cython --version
Cython version 0.28.2

[entire error text.txt](https://github.com/facebookresearch/adversarial_image_defenses/files/1993121/entire.error.text.txt)

**Comment by nishamuktewar** [comment]
Identified the issue: The "setup.py" file pulls the latest copy of "_denoise_cy.pyx" which has been recently updated but the "_tv_bregman.patch" file is based on a prior version.

Not an optimal solution, but for now fixed it by:

1. Cloned the scikit-image repo
2. Replaced the "_denoise_py.pyx" with it's prior version
git checkout 902a9a68add274c4125a358b29e3263b9d94f686 ./skimage/restoration/_denoise_cy.pyx
3. Copied it to the adversarial local repo:
cp ./skimage/restoration/_denoise_cy.pyx ../adversarial_image_defenses/adversarial/lib/transformations/
4. Commented the corresponding lines in setup.py

**Comment by lvdmaaten** [comment]
Thanks for tracking this down! We should probably be adding MD5 checks so that the install script can print out a more informative error message whenever this happens.

For now, let me just hard-code the scikit-image commit number in the setup script. Will send a PR soon.

**Comment by lvdmaaten** [comment]
Yeah, that would probably have been easier in hindsight. Since we're not actively developing this project but only support keeping it in a working state, I'm just going to go with an easy hack for now though.

**Comment by nishamuktewar** [comment]
This work's fine now.
